date: 2022-09-20
dates:
  extract:
  - 2022-08-01
  - 2022-10-01
  festival:
  - 2022-09-20
  - 2022-09-30
report_style: festival_v2
statistics:
  event_type: 0
  events: 213
  hosts: 158
  international: 11
  max_attendees: 61
  sponsors: 46
  total_returns: 69
  total_returns_region: 64
title: September 2022
