title: Leeds Digital Festival GA Summary
data_files_label: service
data_file:
  ga:  
    path: data\social\website.csv
    out_csv: src/_data/metrics/website/ga_monthly.csv
    group_by_date: &period date_M
    group_by_date_col: &col_name month
    #filter_range: &filter 2022-01-01:2022-12-31
    #filter_col: &filter_col_name date
    metrics: &metrics
      - page_views_total
      - unique_page_views_total
      - users_total